name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: 1
  toolchain_style: nightly
  toolchain_lint: nightly
  toolchain_msrv: 1.57

jobs:
  ci-pass:
    name: lgtm
    runs-on: ubuntu-latest
    needs:
      - style
      - lint
      - msrv
      - test
    steps:
      - run: exit 0

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust ${{ env.toolchain_style }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.toolchain_style }}
          profile: minimal
          override: true
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: cargo fmt --all -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  lint:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust ${{ env.toolchain_lint }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.toolchain_lint }}
          profile: minimal
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: cargo clippy --all-targets --all-features
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust ${{ env.toolchain_msrv }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.toolchain_msrv }}
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: cargo check --workspace
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace

  test:
    needs: [msrv]
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        toolchain: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: cargo test --all-targets
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets
      - name: cargo test --doc
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc
